#!/usr/bin/env bash

if [ -z "$VIM" ]; then
  VIM="/Applications/MacVim.app/Contents/MacOS/Vim -v"
fi

$VIM -u NONE -U NONE -N                      \
  --cmd 'set rtp+=../'                       \
  --cmd 'let g:gitgutter_async=0'            \
  --cmd 'source ../plugin/gitgutter.vim'     \
  -S runner.vim                              \
  test_*.vim                                 \
  $*

cat messages.log

grep -q "0 errors, 0 failures" messages.log
status=$?
rm messages.log
exit $status

